name: AzureWebDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

        # Check and Import Existing Resources
      - name: Check and Import Existing Resources
        run: |
          terraform init

          # Import Resource Group
          if az group exists --name "${{ secrets.RESOURCE_GROUP_NAME }}"; then
            echo "Resource group exists. Importing into Terraform state..."
            terraform import module.app_service.azurerm_resource_group.portfolio_resource_group \
              /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}
          fi

          # Import Application Insights
          if az resource show --resource-group "${{ secrets.RESOURCE_GROUP_NAME }}" \
            --resource-type "Microsoft.Insights/components" --name "${{ secrets.APP_INSIGHTS_NAME }}" > /dev/null 2>&1; then
            echo "Application Insights exists. Importing into Terraform state..."
            terraform import module.app_service.azurerm_application_insights.app_insights \
              /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.Insights/components/${{ secrets.APP_INSIGHTS_NAME }}
          fi

          # Import Service Plan
          if az resource show --resource-group "${{ secrets.RESOURCE_GROUP_NAME }}" \
            --resource-type "Microsoft.Web/serverFarms" --name "${{ secrets.SERVICE_PLAN_NAME }}" > /dev/null 2>&1; then
            echo "Service Plan exists. Importing into Terraform state..."
            terraform import module.app_service.azurerm_service_plan.app_service_plan \
              /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.Web/serverFarms/${{ secrets.SERVICE_PLAN_NAME }}
          fi

          # Import Virtual Network
          if az network vnet show --resource-group "${{ secrets.RESOURCE_GROUP_NAME }}" --name "${{ secrets.VNET_NAME }}" > /dev/null 2>&1; then
            echo "Virtual Network exists. Importing into Terraform state..."
            terraform import module.network.azurerm_virtual_network.vnet \
              /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/virtualNetworks/${{ secrets.VNET_NAME }}
          fi

          # Import Subnet
          if az network vnet subnet show --resource-group "${{ secrets.RESOURCE_GROUP_NAME }}" \
            --vnet-name "${{ secrets.VNET_NAME }}" --name "${{ secrets.SUBNET_NAME }}" > /dev/null 2>&1; then
            echo "Subnet exists. Importing into Terraform state..."
            terraform import module.network.azurerm_subnet.subnet \
              /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/virtualNetworks/${{ secrets.VNET_NAME }}/subnets/${{ secrets.SUBNET_NAME }}
          fi

          # Import Linux Web App
          if az webapp show --resource-group "${{ secrets.RESOURCE_GROUP_NAME }}" --name "${{ secrets.APP_SERVICE_NAME }}" > /dev/null 2>&1; then
            echo "Linux Web App exists. Importing into Terraform state..."
            terraform import module.app_service.azurerm_linux_web_app.app_service \
              /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.Web/sites/${{ secrets.APP_SERVICE_NAME }}
          fi
        working-directory: infrastructure
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}


      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure

      # Terraform Plan
      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out=tfplan
        working-directory: infrastructure
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infrastructure
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      # Wait for DNS Propagation
      - name: Wait for DNS Propagation
        run: sleep 10

      # Export Terraform Outputs
      - name: Export Terraform Outputs
        id: export-outputs
        run: |
          terraform output -json > outputs.json
        working-directory: infrastructure

      # Upload Terraform Outputs
      - name: Upload Terraform Outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: infrastructure/outputs.json



  validate_html:
    name: Validate HTML/CSS and Links
    runs-on: ubuntu-latest
    needs: terraform

    env:
      HTML_FILES_PATH: "./webpage/html5-boilerplate-main/dist"
      CSS_FILES_PATH: "./webpage/html5-boilerplate-main/dist"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Terraform Outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs

      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy

      - name: Install stylelint
        run: |
          npm install -g stylelint
          npm install -g stylelint-config-standard

      - name: Validate HTML Files
        run: |
          for file in $(find $HTML_FILES_PATH -name "*.html"); do
            tidy -q -e "$file" || true
          done
        continue-on-error: true

      - name: Validate CSS Files
        run: |
          for file in $(find $CSS_FILES_PATH -name "*.css"); do
            stylelint "$file" || true
          done
        continue-on-error: true

      - name: Check Links in HTML
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder: ${{ env.HTML_FILES_PATH }}
        continue-on-error: true

  build:
    name: Build Node.js App
    runs-on: ubuntu-latest
    needs: [terraform, validate_html]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: webpage/html5-boilerplate-main

      - name: Build the app
        run: npm run build --if-present
        working-directory: webpage/html5-boilerplate-main

      - name: Run tests
        run: npm run test --if-present
        working-directory: webpage/html5-boilerplate-main

      - name: Zip deployment package
        run: zip -r release.zip dist/*
        working-directory: webpage/html5-boilerplate-main

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-app
          path: webpage/html5-boilerplate-main/release.zip        

  deploy:
    name: Deploy Node.js App
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: nodejs-app

      - name: Wait Before Deployment
        run: sleep 10

      - name: Unzip deployment artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: portfolioAppService2
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./dist

  lighthouse:
    name: Lighthouse Audits
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Pull Docker Lighthouse Image
        run: docker pull teambeek/docker-lighthouse

      - name: Run Lighthouse Audits
        run: |
          docker run --rm -v $(pwd):/home/lighthouse/reports \
          teambeek/docker-lighthouse lighthouse https://portfolioAppService2.azurewebsites.net \
          --output=json --output=html --output-path=/home/lighthouse/reports/lighthouse-report