name: Build and Deploy Node.js App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Node.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Zip deployment package
        run: zip release.zip ./* -r

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-app
          path: release.zip

  deploy:
    name: Deploy Node.js App
    runs-on: ubuntu-latest
    needs: [build, validate_html]

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: nodejs-app

      - name: Unzip deployment artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: JBportfolioAppService
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
